credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: Account used if you wanted to bind henkins to AD
          id: "bind_account"
          password: "${BIND}"
          scope: GLOBAL
          username: "AD_BIND_ACCOUNT"
    - credentials:
      - usernamePassword: 
          description: Admin Account
          id: "admin"
          password: "${ADMIN_PASSWORD}"
          scope: GLOBAL
          username: "admin"
jenkins:
  nodes:
    - permanent:
        labelString: "linux docker test"
        mode: NORMAL
        name: "utility-node"
        remoteFS: "/home/user1"
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

    - permanent:
        labelString: "linux docker test"
        mode: NORMAL
        name: "utility-node-2"
        numExecutors: 4
        remoteFS: "/home/user2"
        launcher:
          SSHLauncher:
            host: "192.168.1.1"
            port: 22
            credentialsId: test
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
  views:
    - buildMonitor:
        jobNames:
        - "OVT/OVT"
        - "OVT/OVT-JENKFILE/feature%2Fmake-it-fail"
        - "OVT/OVT-JENKFILE/master"
        name: "OVT"
        recurse: true
        title: "OVT"
    - all:
        name: "all"
# securityRealm:
#   activeDirectory:
#     bindPassword: "${BIND}"
#     customDomain: true
#     domains:
#     - bindName: "CN=YOURACCOUNT.OU=YOUROU,DC=YOURDOMAIN,DC=com"
#       bindPassword: "${BIND}"
#       name: "YOURDOMAIN.COM"
#       servers: "YOURDOMAINCONTROLLER.YOURDOMAIN.COM"
#       site: "YOUR AD SITE"
#       tlsConfiguration: TRUST_ALL_CERTIFICATES
#     groupLookupStrategy: AUTO
#     removeIrrelevantGroups: false
#     startTks: true
  securityRealm:
      local:
        allowsSignup: false
        users:
        - id: "admin"          
          password: "${ADMIN_PASSWORD}"
  authorizationStrategy:
      globalMatrix:
        grantedPermissions:
          - "Overall/Read:anonymous"
          - "Job/Read:anonymous"
          - "View/Read:anonymous"
          - "Overall/Administer:authenticated"
jobs:
  - script: >
      folder('OVT')
  - script: >
      pipelineJob('OVT/OVT') {
        definition {
          cps {
            script("""\
              pipeline {
                agent {label 'master'}
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
  - script: >
      multibranchPipelineJob('OVT/OVT-JENKFILE') {
                branchSources {
                    git {
                        id = 'admin'
                        remote('https://github.com/tknerr/jenkins-pipes-helloworld.git')
                    }
                }
                factory {
                    workflowBranchProjectFactory {
                        scriptPath('Jenkinsfile')
                        }
                }
            }
  - script: queue("OVT/OVT-JENKFILE")
  - file: "/usr/local/BUILD_OVT.groovy"
  - script: queue('OVT/OVT-CLONE1')
  - script: queue('OVT/OVT-CLONE2')
  - script: queue('OVT/OVT-CLONE3')