credentials:
  system:
    domainCredentials:
    - credentials:
      - vaultTokenCredential:
          description: "myroot"
          id: "vault_root"
          scope: GLOBAL
          token: "{AQAAABAAAAAQP2JDYLAVZcMJuuaIjNWRF16Ao+h/LZ1JQ365M3TCUek=}"
jenkins:
  nodes:
    - permanent:
        labelString: "linux docker test"
        mode: NORMAL
        name: "utility-node"
        remoteFS: "/home/user1"
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

    - permanent:
        labelString: "linux docker test"
        mode: NORMAL
        name: "utility-node-2"
        numExecutors: 4
        remoteFS: "/home/user2"
        launcher:
          SSHLauncher:
            host: "192.168.1.1"
            port: 22
            credentialsId: test
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
  views:
    - buildMonitor:
        jobNames:
        - "OVT/OVT"
        name: "OVT"
        recurse: true
        title: "OVT"
    - all:
        name: "all"
jobs:
  - script: >
      folder('OVT')
  - script: >
      pipelineJob('OVT/OVT') {
        definition {
          cps {
            script("""\
              pipeline {
                agent {label 'master'}
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
unclassified:
  hashicorpVault:
    configuration:
      engineVersion: 2
      skipSslVerification: true
      timeout: 60
      vaultCredentialId: "vault_root"
      vaultUrl: "http://localhost:1234"